"""
Backtesting Framework
Evaluate model performance on historical data
Professional evaluation metrics
"""

import torch
import numpy as np
import pandas as pd
from typing import Dict, List, Tuple
from datetime import datetime
import sys
import os

sys.path.append(os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
import config
from loguru import logger


class Backtester:
    """
    Backtest trading signals generated by the model
    Calculate performance metrics
    """

    def __init__(
        self,
        model: torch.nn.Module,
        feature_names: list,
        device: str = "cuda" if torch.cuda.is_available() else "cpu"
    ):
        self.model = model
        self.feature_names = feature_names
        self.device = device
        self.model.eval()

    def generate_signals_historical(
        self,
        df: pd.DataFrame,
        sequence_length: int = config.SEQUENCE_LENGTH
    ) -> pd.DataFrame:
        """
        Generate signals for all historical data

        Args:
            df: DataFrame with features
            sequence_length: Sequence length for model

        Returns:
            DataFrame with signals
        """
        from ai.predict import SignalGenerator

        signal_gen = SignalGenerator(self.model, self.feature_names, self.device)

        signals = []

        # Generate signal for each time point
        for i in range(sequence_length, len(df)):
            # Get sequence
            feature_df = df[self.feature_names].iloc[i-sequence_length:i]
            feature_array = feature_df.values.astype(np.float32)
            feature_tensor = torch.from_numpy(feature_array)

            # Get probabilities
            probabilities = signal_gen.predict_probabilities(feature_tensor)

            # Assess volatility
            df_subset = df.iloc[:i+1]
            volatility_percentile, volatility_regime = signal_gen.assess_volatility(df_subset)

            # Generate signal
            signal_info = signal_gen.generate_signal(probabilities, volatility_percentile)

            signals.append({
                "index": i,
                "timestamp": df.iloc[i]["timestamp"],
                "close": df.iloc[i]["close"],
                "signal": signal_info["signal"],
                "signal_class": signal_info["signal_class"],
                "confidence": signal_info["confidence"],
                "prob_long": signal_info["probabilities"]["long"],
                "prob_short": signal_info["probabilities"]["short"],
                "prob_no_trade": signal_info["probabilities"]["no_trade"],
                "volatility_regime": volatility_regime
            })

        signals_df = pd.DataFrame(signals)
        return signals_df

    def calculate_returns(
        self,
        signals_df: pd.DataFrame,
        holding_periods: List[int] = [1, 5, 10]
    ) -> pd.DataFrame:
        """
        Calculate returns for each signal

        Args:
            signals_df: DataFrame with signals
            holding_periods: List of holding periods to evaluate

        Returns:
            DataFrame with returns
        """
        for period in holding_periods:
            # Forward return
            signals_df[f"return_{period}"] = (
                signals_df["close"].shift(-period) / signals_df["close"] - 1
            ) * 100

            # Signal return (if we followed the signal)
            signals_df[f"signal_return_{period}"] = 0.0

            # LONG signals: positive return
            long_mask = signals_df["signal"] == "LONG"
            signals_df.loc[long_mask, f"signal_return_{period}"] = signals_df.loc[long_mask, f"return_{period}"]

            # SHORT signals: negative return (profit from price drop)
            short_mask = signals_df["signal"] == "SHORT"
            signals_df.loc[short_mask, f"signal_return_{period}"] = -signals_df.loc[short_mask, f"return_{period}"]

            # NO TRADE: 0 return

        return signals_df

    def calculate_metrics(
        self,
        signals_df: pd.DataFrame,
        holding_period: int = 10
    ) -> Dict:
        """
        Calculate performance metrics

        Args:
            signals_df: DataFrame with signals and returns
            holding_period: Holding period to evaluate

        Returns:
            Dictionary of metrics
        """
        return_col = f"signal_return_{holding_period}"

        # Filter out NO TRADE signals for trade metrics
        trade_mask = signals_df["signal"] != "NO TRADE"
        trades_df = signals_df[trade_mask].copy()

        if len(trades_df) == 0:
            return {
                "total_signals": len(signals_df),
                "num_trades": 0,
                "error": "No trades generated"
            }

        # Basic stats
        num_trades = len(trades_df)
        num_long = (trades_df["signal"] == "LONG").sum()
        num_short = (trades_df["signal"] == "SHORT").sum()
        num_no_trade = (signals_df["signal"] == "NO TRADE").sum()

        # Returns
        avg_return = trades_df[return_col].mean()
        median_return = trades_df[return_col].median()
        total_return = trades_df[return_col].sum()

        # Win rate
        winning_trades = (trades_df[return_col] > 0).sum()
        win_rate = (winning_trades / num_trades) * 100 if num_trades > 0 else 0

        # Risk metrics
        std_return = trades_df[return_col].std()
        sharpe_ratio = (avg_return / std_return) if std_return > 0 else 0

        # Max drawdown
        cumulative_returns = (1 + trades_df[return_col] / 100).cumprod()
        running_max = cumulative_returns.expanding().max()
        drawdown = (cumulative_returns - running_max) / running_max * 100
        max_drawdown = drawdown.min()

        # By signal type
        long_returns = trades_df[trades_df["signal"] == "LONG"][return_col]
        short_returns = trades_df[trades_df["signal"] == "SHORT"][return_col]

        metrics = {
            "total_signals": len(signals_df),
            "num_trades": num_trades,
            "num_long": num_long,
            "num_short": num_short,
            "num_no_trade": num_no_trade,
            "trade_frequency": (num_trades / len(signals_df)) * 100,
            "avg_return_per_trade": round(avg_return, 2),
            "median_return_per_trade": round(median_return, 2),
            "total_return": round(total_return, 2),
            "win_rate": round(win_rate, 2),
            "std_return": round(std_return, 2),
            "sharpe_ratio": round(sharpe_ratio, 3),
            "max_drawdown": round(max_drawdown, 2),
            "long_avg_return": round(long_returns.mean(), 2) if len(long_returns) > 0 else 0,
            "short_avg_return": round(short_returns.mean(), 2) if len(short_returns) > 0 else 0,
            "holding_period": holding_period
        }

        return metrics

    def run_backtest(
        self,
        df: pd.DataFrame,
        holding_periods: List[int] = [1, 5, 10]
    ) -> Dict:
        """
        Run full backtest

        Args:
            df: DataFrame with features
            holding_periods: List of holding periods

        Returns:
            Dictionary with results
        """
        logger.info("Generating historical signals...")
        signals_df = self.generate_signals_historical(df)

        logger.info("Calculating returns...")
        signals_df = self.calculate_returns(signals_df, holding_periods)

        # Calculate metrics for each holding period
        results = {
            "signals_df": signals_df,
            "metrics": {}
        }

        for period in holding_periods:
            logger.info(f"Calculating metrics for {period}-candle holding period...")
            metrics = self.calculate_metrics(signals_df, holding_period=period)
            results["metrics"][f"period_{period}"] = metrics

        return results

    def print_summary(self, results: Dict):
        """Print backtest summary"""
        print("\n" + "="*60)
        print("BACKTEST SUMMARY")
        print("="*60)

        for period_key, metrics in results["metrics"].items():
            period = metrics.get("holding_period", "?")
            print(f"\nHolding Period: {period} candles")
            print("-" * 60)
            print(f"Total Signals: {metrics['total_signals']}")
            print(f"Trades Executed: {metrics['num_trades']} ({metrics['trade_frequency']:.1f}%)")
            print(f"  - LONG: {metrics['num_long']}")
            print(f"  - SHORT: {metrics['num_short']}")
            print(f"  - NO TRADE: {metrics['num_no_trade']}")
            print(f"\nPerformance:")
            print(f"  Win Rate: {metrics['win_rate']:.1f}%")
            print(f"  Avg Return per Trade: {metrics['avg_return_per_trade']:.2f}%")
            print(f"  Total Return: {metrics['total_return']:.2f}%")
            print(f"  Sharpe Ratio: {metrics['sharpe_ratio']:.3f}")
            print(f"  Max Drawdown: {metrics['max_drawdown']:.2f}%")
            print(f"\nBy Signal Type:")
            print(f"  LONG Avg: {metrics['long_avg_return']:.2f}%")
            print(f"  SHORT Avg: {metrics['short_avg_return']:.2f}%")

        print("\n" + "="*60)


def backtest_model(
    symbol: str,
    timeframe: str,
    model_path: str,
    test_period_days: int = 90
) -> Dict:
    """
    Complete backtest pipeline

    Args:
        symbol: Trading pair
        timeframe: Timeframe
        model_path: Path to trained model
        test_period_days: Number of days to test

    Returns:
        Backtest results
    """
    from data.market import BinanceDataFetcher
    from data.features import FeatureEngine
    from ai.model import create_model

    # Load model
    logger.info(f"Loading model from {model_path}")
    checkpoint = torch.load(model_path, map_location="cpu")

    num_features = checkpoint["num_features"]
    model_type = checkpoint["model_type"]
    feature_names = checkpoint["feature_names"]

    device = "cuda" if torch.cuda.is_available() else "cpu"
    model = create_model(num_features, model_type=model_type, device=device)
    model.load_state_dict(checkpoint["model_state_dict"])

    # Load data
    logger.info(f"Loading data for {symbol} {timeframe}")
    fetcher = BinanceDataFetcher()
    df = fetcher.fetch_historical_data(symbol, timeframe, days=test_period_days + 30)

    # Create features
    logger.info("Computing features...")
    engine = FeatureEngine()
    df = engine.create_all_features(df)

    # Use only test period
    df = df.iloc[-int(len(df) * 0.3):]  # Last 30% for testing

    # Run backtest
    backtester = Backtester(model, feature_names, device=device)
    results = backtester.run_backtest(df)

    # Print summary
    backtester.print_summary(results)

    return results


if __name__ == "__main__":
    # Setup logging
    logger.add(
        os.path.join(config.LOGS_DIR, "backtest.log"),
        rotation="10 MB",
        level="INFO"
    )

    # Run backtest
    symbol = "BTCUSDT"
    timeframe = "1h"
    model_filename = f"{symbol}_{timeframe}_{config.MODEL_TYPE}.pt"
    model_path = os.path.join(config.MODELS_DIR, model_filename)

    results = backtest_model(symbol, timeframe, model_path)
